### ISSUE TITLE
HOW TO RUN IT?

### ISSUE THREAD

**Issue by Programmers3001** [hanhdt/esp32-flash-tool#330]
There are already 4 issues on the same question and you couldn't answer any of them? IT DOESN'T HAVE AN .exe NOR ANY OTHER INSTRUCTION ON HOW TO RUN IT! At least answer some of the issues please!

**Comment by hanhdt** [comment]
Sorry, I have been busy so I didn't have time to look at the issues here.
Not sure if you have managed to run the tool on your side yet.

This is a desktop application built on top of Electron (Node.js framework for desktop).
In order to get an execution file for your OS, you have to build it on the same environment. Because I don't have Windows recently, that's why I can't build .exe.
You might want to check **Releases** page at one of the previous versions if it works for you - https://github.com/hanhdt/esp32-flash-tool/releases/tag/v0.1.0

I will try to update more documentation when I have time.
Thank you.
